### PR TITLE
Made a small refactoring

### PR DESCRIPTION
**Pull request by KalitaAlexey**
Removed derive_new because it had been unused.
Renamed the function "read" to "with_analysis".
Ran "cargo clippy -A new_without_default_derive" and fixed all warnings.
Added a .gitignore, which ignores only target.

Let me know if I did something what you don't accept.

### CODE REVIEW

**Comment by nrc** [comment]
Looks good, thank you! Just to check since I don't have Travis here, did you run `cargo test`?

**Comment by KalitaAlexey** [comment]
@nrc,
I didn't.
Let me check.

**Comment by KalitaAlexey** [comment]
@nrc,
Now it is all okay.

**Comment by nrc** [comment]
Thanks!

**Pull request merged**
