### PR TITLE
Add parent to SymbolResult

### PR DESCRIPTION
**Pull request by pkoenig10**
This will allow the RLS to populate the `container_name` field to provide hierarchical symbol information to clients.

https://github.com/rust-lang-nursery/rls/blob/5d3f9e1fe43c1feaec6a68c5326800c08406ff07/src/actions/requests.rs#L124

https://github.com/rust-lang-nursery/rls-vscode/issues/124

### CODE REVIEW

**Comment by nrc** [comment]
This seems good, but I wonder if we could do better? Would it be better to compute the container name in rls-analysis, rather than letting the RLS do it? Or should we have some API where you walk the tree in rls-analysis or some other such setup?

**Comment by pkoenig10** [comment]
I'm not entirely sure who is expected to consume symbol information. But by computing the container name we are making assumptions about what callers want (maybe they don't care about the parent container name). It is not any more efficient for rls-analysis to compute this than for callers to do it themselves because the def id is a sufficient identifier for callers to get more information if they need it.

**Comment by nrc** [comment]
Yeah, that seems fair. Let's do it this way.

**Comment by pkoenig10** [comment]
@nrc Could you release a version with this change?

**Comment by nrc** [comment]
Published 0.11.2

**Pull request merged**
